- hosts: dns_server
  remote_user: "{{rhel_user}}"
  become: yes
  tasks:
  - name: reboot {{ inventory_hostname }}"
    shell: sleep 2 && shutdown -r now "Ansible package updates triggered"
    async: 1
    poll: 0
    ignore_errors: true
    become: true
  - name: Wait 60 seconds, but only start checking after 30 seconds
    wait_for_connection:
      delay: 30
      timeout: 60
