---

- name: register master and lb nodes with gluster client repos to RHSM
  vars:
    - rhsm_repos: "{{ okd_repos_with_glus_client }}"
  include_role:
    name: swygue-redhat-subscription
  tags: repos
  when: glusterfs and (ansible_hostname in groups['masters'] or
                       ansible_hostname in groups['lbs'])

- name: register nodes and infra with gluster server repos to RHSM
  vars:
    - rhsm_repos: "{{ okd_repos_with_glus_client }}"
  include_role:
    name: swygue-redhat-subscription
  tags: repos
  when: glusterfs and (ansible_hostname in groups['computes'] or
                       ansible_hostname in groups['infra'])

- name: register nodes to RHSM
  vars:
    - rhsm_repos: "{{ okd_repos_with_glus_client }}"
  include_role:
    name: swygue-redhat-subscription
  tags: repos
  when: not glusterfs|bool

- name: install glusterfs-fuse when using gluster storage
  yum:
    name: glusterfs-fuse
  when: glusterfs and inventory_hostname not in groups['masters']
  tags:
    - pkgs

- name: install required node packages
  shell: >
    rpm -q "{{ item }}" || yum install -y "{{ item }}" && echo yes
  args:
    warn: false
  loop: "{{ okd_nodes_pkgs }}"
  register: pkg_installed
  changed_when: pkg_installed.stdout == 'yes'
  tags:
    - pkgs

