---
- name: setup KVM host
  hosts: localhost
  become: yes
  vars_files:
    - vars/all.yml
    - vars/kvm_host.yml
    - vars/vault.yml

  tasks:
    - name: ensure backup folder is created
      file:
        path: "{{ project_dir }}/backups"
        state: directory
        mode: '0755'

    - fail: msg="Checking to see if host_device is defined."
      when: host_device is not defined

    - fail: msg="Checking to see if vg_name is defined."
      when: vg_name is not defined

    - name: create libvirt logical volume
      include_role:
         name: swygue-lvm
      when: create_lvm|bool

    - fail: msg="Checking to see if network_interface_name is defined."
      when: network_interface_name is not defined

    - name: Check whether ifcfg-{{ network_interface_name }} contains "UUID"
      command: grep -Fxq "UUID" /etc/sysconfig/network-scripts/ifcfg-{{ network_interface_name }}
      register: interfacecheck
      check_mode: no
      ignore_errors: yes

    - name: check if ifcfg-{{ network_interface_name }} backup file exists
      stat:
        path: "{{ project_dir }}/backups/ifcfg-{{ network_interface_name }}"
      register: interfacecheck
      delegate_to: 127.0.0.1

    - name: backup  ifcfg-{{ network_interface_name }}
      shell: "cat /etc/sysconfig/network-scripts/ifcfg-{{ network_interface_name }} > {{ project_dir }}/backups/ifcfg-{{ network_interface_name }}"
      when: not interfacecheck.stat.exists
      delegate_to: 127.0.0.1

    - name: running KVM host setup
      include_role:
         name: qubinode_kvmhost_setup

    - name: validate KVM host setup
      include_role:
         name: edge_hosts_validate
